### ISSUE TITLE
netvar manager

### ISSUE THREAD

**Issue by NullFlex** [fluc-uc/EmuSDK#2]
can we get a new b1g netvar manager?
preferably one that works. 
Been wanting to write something on this base but I didnt feel like pasting a netvar manager.

**Comment by terryadavis** [comment]
@NullFlex the current one on it works and is probably the fastest public one

**Comment by NullFlex** [comment]
https://b.catgirlsare.sexy/gekE.png
p100 my man

**Comment by NullFlex** [comment]
u lied @terryadavis it didnt work

**Comment by terryadavis** [comment]
@NullFlex that's not netvar_manager related learncpp.com

**Comment by NullFlex** [comment]
i know, but im saying the netvar manager doesnt even work
nice cheat l0l

**Comment by NullFlex** [comment]
I fixed the netvar manager. looks like u braindead buffoons couldn't do shit on ur own.

**Comment by terryadavis** [comment]
@NullFlex I don't even have the base downloaded nor do I use it for my own cheat lmao
